# Generated by Django 5.2.1 on 2025-06-06 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0003_actionlog_assigned_to_actionlog_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlogcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Action Log Comment', 'verbose_name_plural': 'Action Log Comments'},
        ),
        migrations.AddField(
            model_name='actionlogcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='action_logs.actionlogcomment'),
        ),
        migrations.AlterField(
            model_name='actionlogcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_log_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
