# Generated by Django 5.0.2 on 2025-06-06 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0004_alter_actionlogcomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('action_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='action_logs.actionlog')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(related_name='assignment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action Log Assignment History',
                'verbose_name_plural': 'Action Log Assignment Histories',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
