# Generated by Django 5.2.1 on 2025-06-06 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0005_actionlogassignmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_log_notifications', to='action_logs.actionlog')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='action_logs.actionlogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_log_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action Log Notification',
                'verbose_name_plural': 'Action Log Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
