# Generated by Django 5.2.1 on 2025-06-06 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0006_actionlognotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlogcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='actionlogcomment',
            old_name='parent_comment',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='actionlogcomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionlogcomment',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionlogcomment',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actionlogcomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
