# Generated by Django 5.2.1 on 2025-06-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0007_alter_actionlogcomment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlogcomment',
            old_name='parent',
            new_name='parent_comment',
        ),
    ]
