# Generated by Django 5.0.2 on 2025-06-11 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0008_rename_parent_actionlogcomment_parent_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='closure_approval_stage',
            field=models.CharField(choices=[('none', 'None'), ('unit_head', 'Unit Head'), ('assistant_commissioner', 'Assistant Commissioner'), ('commissioner', 'Commissioner'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='closure_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closure_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
