# Generated by Django 5.2.1 on 2025-05-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_assign_to_commissioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_all_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
