# Generated by Django 5.2.1 on 2025-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_can_assign_to_commissioner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='can_create_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_update_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('economist', 'Economist'), ('senior_economist', 'Senior Economist'), ('principal_economist', 'Principal Economist'), ('commissioner', 'Commissioner'), ('assistant_commissioner', 'Assistant Commissioner'), ('super_admin', 'Super Admin')], max_length=50, unique=True),
        ),
    ]
