# Generated by Django 5.2.1 on 2025-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='reason',
            field=models.CharField(choices=[('leave', 'Leave'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
